# >>> 设置目录树
SET_PROPERTY(GLOBAL PROPERTY USE_FOLDERS ON)
SET_PROPERTY(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMakeTargets")
SET_TARGET_PROPERTIES(${BIN_TARGET} PROPERTIES FOLDER "")

GET_TARGET_PROPERTY(TARGET_SOURCES ${BIN_TARGET} SOURCES)
SOURCE_GROUP(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${SOURCE_FILES} ${HEADER_FILES})
SOURCE_GROUP("" FILES main.cc)
# <<< 设置目录树

# >>> 导出
STRING(REPLACE " " "-" CMAKE_GENERATOR_MODIFIED "${CMAKE_GENERATOR}")
SET(EXPORT_DIR ${PROJECT_SOURCE_DIR}/project/${CMAKE_GENERATOR_MODIFIED})
MESSAGE(STATUS "移除路径: ${EXPORT_DIR}")
FILE(REMOVE_RECURSE ${EXPORT_DIR})
MESSAGE(STATUS "创建路径: ${EXPORT_DIR}")
FILE(MAKE_DIRECTORY ${EXPORT_DIR})

FILE(GLOB VCX_PROJ
        ${CMAKE_BINARY_DIR}/*.sln
        ${CMAKE_BINARY_DIR}/*.vcxproj
        ${CMAKE_BINARY_DIR}/*.filters)

FOREACH (file IN LISTS VCX_PROJ)
    MESSAGE(STATUS "${file}")
    FILE(COPY ${file} DESTINATION ${EXPORT_DIR})
ENDFOREACH ()
# <<< 导出